data_file: "datasets/data_mouse_gut.h5"
outdir: "./outputs"
stage: "train"
batch_size: "auto"
encoder_layers: [256, 128]
decoder_layers: [256, 128]
GP_dim: 2
Normal_dim: 8
lr: 0.0002
maxiter: 3000
patience: 200
pert_cells: "D12"
target_cell_day: 30.
target_cell_perturbation: "0.0"
project_index: "gut"
model_file: "model.pt"
wandb: true
wandb_project: "concert"
wandb_run: "test"
wandb_mode: "online"


