data_file: "datasets/mouse_stroke.h5"
outdir: "./outputs"
stage: "train"
batch_size: "auto"
encoder_layers: [256, 64]
decoder_layers: [64, 256]
GP_dim: 2
Normal_dim: 8
z_range: 60
kernel_scale: 60
loc_range: 60
allow_batch_kernel_scale: true
lr: 0.0001
maxiter: 3000
patience: 200
pert_cells: "pert_cells/pert_cells_stroke_sham1_CIA.txt"
pert_batch: "Sham1"
target_cell_perturbation: "ICA"
project_index: "trans"
model_file: "model_stroke_3D.pt"
wandb: true
wandb_project: "concert"
wandb_run: "test"
wandb_mode: "online"
